/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AttendanceRecord {
    totalClasses: bigint;
    studentId: bigint;
    attendanceCount: bigint;
}
export interface DepartmentSummary {
    totalStudents: bigint;
    totalSubjects: bigint;
    totalTeachers: bigint;
    department: string;
}
export type LoginResult = {
    __kind__: "failure";
    failure: string;
} | {
    __kind__: "success";
    success: UserRole;
};
export interface SchoolSummary {
    averageAttendance: number;
    totalStudents: bigint;
    totalSubjects: bigint;
    totalTeachers: bigint;
    departmentStats: Array<DepartmentSummary>;
}
export interface Teacher {
    id: bigint;
    name: string;
    department: string;
}
export interface Subject {
    id: bigint;
    name: string;
    attendanceRecords: Array<AttendanceRecord>;
    teacherId: bigint;
}
export interface UserProfile {
    name: string;
}
export interface Student {
    id: bigint;
    subjects: Array<bigint>;
    name: string;
}
export enum LoginRole {
    admin = "admin",
    teacher = "teacher",
    student = "student"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addDepartmentSummary(summary: DepartmentSummary): Promise<void>;
    addStudent(student: Student): Promise<void>;
    addSubject(subject: Subject): Promise<void>;
    addTeacher(teacher: Teacher): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    login(role: LoginRole, credential: bigint): Promise<LoginResult>;
    queryAllDepartments(): Promise<Array<DepartmentSummary>>;
    queryAllSubjects(): Promise<Array<Subject>>;
    queryDepartmentSummary(department: string): Promise<DepartmentSummary>;
    querySchoolSummary(): Promise<SchoolSummary>;
    querySubjectSummary(subjectId: bigint): Promise<{
        subject: Subject;
        department?: DepartmentSummary;
    }>;
    querySubjectsByStudent(studentId: bigint): Promise<Array<Subject>>;
    querySubjectsByTeacher(teacherId: bigint): Promise<Array<Subject>>;
    queryTeacherSummary(teacherId: bigint): Promise<{
        subjects: Array<Subject>;
        teacher: Teacher;
        department?: DepartmentSummary;
    }>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { DepartmentSummary as _DepartmentSummary, LoginResult as _LoginResult, LoginRole as _LoginRole, Subject as _Subject, Teacher as _Teacher, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDepartmentSummary(arg0: DepartmentSummary): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDepartmentSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDepartmentSummary(arg0);
            return result;
        }
    }
    async addStudent(arg0: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0);
            return result;
        }
    }
    async addSubject(arg0: Subject): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubject(arg0);
            return result;
        }
    }
    async addTeacher(arg0: Teacher): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeacher(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async login(arg0: LoginRole, arg1: bigint): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(to_candid_LoginRole_n6(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_LoginResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(to_candid_LoginRole_n6(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_LoginResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async queryAllDepartments(): Promise<Array<DepartmentSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.queryAllDepartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryAllDepartments();
            return result;
        }
    }
    async queryAllSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.queryAllSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryAllSubjects();
            return result;
        }
    }
    async queryDepartmentSummary(arg0: string): Promise<DepartmentSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.queryDepartmentSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryDepartmentSummary(arg0);
            return result;
        }
    }
    async querySchoolSummary(): Promise<SchoolSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.querySchoolSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.querySchoolSummary();
            return result;
        }
    }
    async querySubjectSummary(arg0: bigint): Promise<{
        subject: Subject;
        department?: DepartmentSummary;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.querySubjectSummary(arg0);
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.querySubjectSummary(arg0);
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async querySubjectsByStudent(arg0: bigint): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.querySubjectsByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.querySubjectsByStudent(arg0);
            return result;
        }
    }
    async querySubjectsByTeacher(arg0: bigint): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.querySubjectsByTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.querySubjectsByTeacher(arg0);
            return result;
        }
    }
    async queryTeacherSummary(arg0: bigint): Promise<{
        subjects: Array<Subject>;
        teacher: Teacher;
        department?: DepartmentSummary;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.queryTeacherSummary(arg0);
                return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryTeacherSummary(arg0);
            return from_candid_record_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_LoginResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DepartmentSummary]): DepartmentSummary | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject: _Subject;
    department: [] | [_DepartmentSummary];
}): {
    subject: Subject;
    department?: DepartmentSummary;
} {
    return {
        subject: value.subject,
        department: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.department))
    };
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subjects: Array<_Subject>;
    teacher: _Teacher;
    department: [] | [_DepartmentSummary];
}): {
    subjects: Array<Subject>;
    teacher: Teacher;
    department?: DepartmentSummary;
} {
    return {
        subjects: value.subjects,
        teacher: value.teacher,
        department: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.department))
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    failure: string;
} | {
    success: _UserRole;
}): {
    __kind__: "failure";
    failure: string;
} | {
    __kind__: "success";
    success: UserRole;
} {
    return "failure" in value ? {
        __kind__: "failure",
        failure: value.failure
    } : "success" in value ? {
        __kind__: "success",
        success: from_candid_UserRole_n4(_uploadFile, _downloadFile, value.success)
    } : value;
}
function to_candid_LoginRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoginRole): _LoginRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoginRole): {
    admin: null;
} | {
    teacher: null;
} | {
    student: null;
} {
    return value == LoginRole.admin ? {
        admin: null
    } : value == LoginRole.teacher ? {
        teacher: null
    } : value == LoginRole.student ? {
        student: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
