/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'totalClasses' : bigint,
  'studentId' : bigint,
  'attendanceCount' : bigint,
}
export interface DepartmentSummary {
  'totalStudents' : bigint,
  'totalSubjects' : bigint,
  'totalTeachers' : bigint,
  'department' : string,
}
export type LoginResult = { 'failure' : string } |
  { 'success' : UserRole };
export type LoginRole = { 'admin' : null } |
  { 'teacher' : null } |
  { 'student' : null };
export interface SchoolSummary {
  'averageAttendance' : number,
  'totalStudents' : bigint,
  'totalSubjects' : bigint,
  'totalTeachers' : bigint,
  'departmentStats' : Array<DepartmentSummary>,
}
export interface Student {
  'id' : bigint,
  'subjects' : Array<bigint>,
  'name' : string,
}
export interface Subject {
  'id' : bigint,
  'name' : string,
  'attendanceRecords' : Array<AttendanceRecord>,
  'teacherId' : bigint,
}
export interface Teacher {
  'id' : bigint,
  'name' : string,
  'department' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addDepartmentSummary' : ActorMethod<[DepartmentSummary], undefined>,
  'addStudent' : ActorMethod<[Student], undefined>,
  'addSubject' : ActorMethod<[Subject], undefined>,
  'addTeacher' : ActorMethod<[Teacher], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[LoginRole, bigint], LoginResult>,
  'queryAllDepartments' : ActorMethod<[], Array<DepartmentSummary>>,
  'queryAllSubjects' : ActorMethod<[], Array<Subject>>,
  'queryDepartmentSummary' : ActorMethod<[string], DepartmentSummary>,
  'querySchoolSummary' : ActorMethod<[], SchoolSummary>,
  'querySubjectSummary' : ActorMethod<
    [bigint],
    { 'subject' : Subject, 'department' : [] | [DepartmentSummary] }
  >,
  'querySubjectsByStudent' : ActorMethod<[bigint], Array<Subject>>,
  'querySubjectsByTeacher' : ActorMethod<[bigint], Array<Subject>>,
  'queryTeacherSummary' : ActorMethod<
    [bigint],
    {
      'subjects' : Array<Subject>,
      'teacher' : Teacher,
      'department' : [] | [DepartmentSummary],
    }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];