/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DepartmentSummary = IDL.Record({
  'totalStudents' : IDL.Nat,
  'totalSubjects' : IDL.Nat,
  'totalTeachers' : IDL.Nat,
  'department' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'subjects' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
});
export const AttendanceRecord = IDL.Record({
  'totalClasses' : IDL.Nat,
  'studentId' : IDL.Nat,
  'attendanceCount' : IDL.Nat,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'attendanceRecords' : IDL.Vec(AttendanceRecord),
  'teacherId' : IDL.Nat,
});
export const Teacher = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'department' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LoginRole = IDL.Variant({
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
  'student' : IDL.Null,
});
export const LoginResult = IDL.Variant({
  'failure' : IDL.Text,
  'success' : UserRole,
});
export const SchoolSummary = IDL.Record({
  'averageAttendance' : IDL.Float64,
  'totalStudents' : IDL.Nat,
  'totalSubjects' : IDL.Nat,
  'totalTeachers' : IDL.Nat,
  'departmentStats' : IDL.Vec(DepartmentSummary),
});

export const idlService = IDL.Service({
  'addDepartmentSummary' : IDL.Func([DepartmentSummary], [], []),
  'addStudent' : IDL.Func([Student], [], []),
  'addSubject' : IDL.Func([Subject], [], []),
  'addTeacher' : IDL.Func([Teacher], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([LoginRole, IDL.Nat], [LoginResult], []),
  'queryAllDepartments' : IDL.Func([], [IDL.Vec(DepartmentSummary)], ['query']),
  'queryAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'queryDepartmentSummary' : IDL.Func(
      [IDL.Text],
      [DepartmentSummary],
      ['query'],
    ),
  'querySchoolSummary' : IDL.Func([], [SchoolSummary], ['query']),
  'querySubjectSummary' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'subject' : Subject,
          'department' : IDL.Opt(DepartmentSummary),
        }),
      ],
      ['query'],
    ),
  'querySubjectsByStudent' : IDL.Func([IDL.Nat], [IDL.Vec(Subject)], ['query']),
  'querySubjectsByTeacher' : IDL.Func([IDL.Nat], [IDL.Vec(Subject)], ['query']),
  'queryTeacherSummary' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'subjects' : IDL.Vec(Subject),
          'teacher' : Teacher,
          'department' : IDL.Opt(DepartmentSummary),
        }),
      ],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DepartmentSummary = IDL.Record({
    'totalStudents' : IDL.Nat,
    'totalSubjects' : IDL.Nat,
    'totalTeachers' : IDL.Nat,
    'department' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'subjects' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
  });
  const AttendanceRecord = IDL.Record({
    'totalClasses' : IDL.Nat,
    'studentId' : IDL.Nat,
    'attendanceCount' : IDL.Nat,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'attendanceRecords' : IDL.Vec(AttendanceRecord),
    'teacherId' : IDL.Nat,
  });
  const Teacher = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'department' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LoginRole = IDL.Variant({
    'admin' : IDL.Null,
    'teacher' : IDL.Null,
    'student' : IDL.Null,
  });
  const LoginResult = IDL.Variant({
    'failure' : IDL.Text,
    'success' : UserRole,
  });
  const SchoolSummary = IDL.Record({
    'averageAttendance' : IDL.Float64,
    'totalStudents' : IDL.Nat,
    'totalSubjects' : IDL.Nat,
    'totalTeachers' : IDL.Nat,
    'departmentStats' : IDL.Vec(DepartmentSummary),
  });
  
  return IDL.Service({
    'addDepartmentSummary' : IDL.Func([DepartmentSummary], [], []),
    'addStudent' : IDL.Func([Student], [], []),
    'addSubject' : IDL.Func([Subject], [], []),
    'addTeacher' : IDL.Func([Teacher], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([LoginRole, IDL.Nat], [LoginResult], []),
    'queryAllDepartments' : IDL.Func(
        [],
        [IDL.Vec(DepartmentSummary)],
        ['query'],
      ),
    'queryAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'queryDepartmentSummary' : IDL.Func(
        [IDL.Text],
        [DepartmentSummary],
        ['query'],
      ),
    'querySchoolSummary' : IDL.Func([], [SchoolSummary], ['query']),
    'querySubjectSummary' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'subject' : Subject,
            'department' : IDL.Opt(DepartmentSummary),
          }),
        ],
        ['query'],
      ),
    'querySubjectsByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Subject)],
        ['query'],
      ),
    'querySubjectsByTeacher' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Subject)],
        ['query'],
      ),
    'queryTeacherSummary' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'subjects' : IDL.Vec(Subject),
            'teacher' : Teacher,
            'department' : IDL.Opt(DepartmentSummary),
          }),
        ],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };